[package]
name = "eternitywall-site"
version = "0.1.0"
edition = "2018"

[dependencies]
blocks_iterator = "1.0.0"
env_logger = "0.9"
chrono = "0.4.19"
maud = "0.23"
whatlang = "0.13"
structopt = "0.3.21" # cannot use re-exported cause I need macros

[dev-dependencies]
base64 = "0.13.0"
